server:
  port: 2335

spring:
  application:
    name: one-team-uap
  zipkin:
    base-url: http://${eureka.instance.hostname}:9411
  boot:
    admin:
      client:
        url: http://${eureka.instance.hostname}:2338

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:2333/eureka/
  instance:
    hostname: localhost

# 开启熔断器
feign:
  hystrix:
    enabled: true