spring:
  application:
    name: one-team-uap

server:
  port: 2355

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:2333/eureka/
  instance:
    hostname: localhost

# 开启熔断器
feign:
  hystrix:
    enabled: true